### ISSUE TITLE
Designator of some components are missing in Gerber Files.  

### ISSUE THREAD

**Issue by AbidHussain70** [iliasam/OpenTOFLidar#1]
Hi, First wanna say thanks. Very well explained and well documented.
I want to make one of these, but when I upload the gerber files it seems some of the components footprints have no designator. Can you provide a complete Gerber files. Thanks 
 Below are the pictures of both versions. 
![image](https://user-images.githubusercontent.com/23444211/77288374-a39c7480-6d12-11ea-9f3f-b2c2efdd617b.png)

![image](https://user-images.githubusercontent.com/23444211/77288454-d34b7c80-6d12-11ea-9f9f-2053093ada4d.png)

![image](https://user-images.githubusercontent.com/23444211/77288481-e65e4c80-6d12-11ea-8840-f4446274efaf.png)
![image](https://user-images.githubusercontent.com/23444211/77288543-04c44800-6d13-11ea-9ad5-4e94aa6bb6ee.png)

**Comment by iliasam** [comment]
You are right. 
"PCB_project_v1" have less designators at Silkscreen.
"PCB_project_v4" have more designators at Silkscreen. 
Also, there are special images at "PCB_project_v4" folder: "PCB_3D_view_down", "PCB_3D_view_up" with manually written designators.

**Comment by AbidHussain70** [comment]
Thanks for the quick response.
Yes I saw those images. I want to send the PCB to manufacturer for soldering, anyhow i will try to solder it. 
I have another question, both the version PCB_project_v1 and PCB_project_v4 work fine? 
I want to use v4.

**Comment by iliasam** [comment]
See board differences description: https://github.com/iliasam/OpenTOFLidar/blob/develop/PCB/README.md
I'm not sure that Silkscreen marking is enough for PCB manufacturer to assemble the board.
They could ask for a special assembling drawing or some kind of "pick and place" file.

**Comment by AbidHussain70** [comment]
I can get my PCB with these files, but they will not solder it, because of designator issue. From the video it seems this scanner works fine. So I will order the PCB and I will solder the components by myself and I will update you about the results. 
Thanks

**Comment by AbidHussain70** [comment]
Did you use QUARTZ_32K in "PCB_project_v4"? I saw the two images "PCB_3D_view_down" and PCB_3D_view_up" and also I check the Gerber files, but I could not find the location of the component in the PCB.

**Comment by iliasam** [comment]
Be careful with WIFI in "PCB_project_v4 ". I had to install a special metallic plate between WIFI antenna and LIDAR to reduce noise from WIFI. It is not shown at photos.
