### ISSUE TITLE
Step 6.Install APD DC-DC co......

### ISSUE THREAD

**Issue by br76530067** [iliasam/OpenTOFLidar#10]
When doing "6.Install APD DC-DC components (Q1 and others). Check "APD_V" - it must change by manual commands from utility."

I found I only could adjust the APD Volt in scope 0 ~ 59.8V, like below pictures, whatever I changed the APD PWM and APD Targ.Volt. Should it be correct?
![image](https://user-images.githubusercontent.com/41344495/129368896-3ee1d1dd-5fa0-4306-b00f-0aeead00c7fe.png)

![image](https://user-images.githubusercontent.com/41344495/129368882-6ab00389-8991-4041-9f62-158fda048cb9.png)

![image](https://user-images.githubusercontent.com/41344495/129368913-bb7230cb-e032-426a-91b0-33e11b969148.png)

![image](https://user-images.githubusercontent.com/41344495/129368932-ba701af1-5cfb-4c09-88cb-622a3b3183ac.png)

![image](https://user-images.githubusercontent.com/41344495/129368943-76081e90-6765-43f1-a91c-01a071f9514b.png)

![image](https://user-images.githubusercontent.com/41344495/129368961-eafa94cf-4342-49e0-bbfd-8ff6373b69a8.png)

**Comment by iliasam** [comment]
This is not correct. Voltage should grow higher.
Don't try to switch to Auto mode until you get well working manual mode.
Have you measured APD voltage by voltmeter? Is the value the same as displayed in utility?
Also you can check this (type of inductor): https://github.com/iliasam/OpenTOFLidar/issues/5#issuecomment-690827160

**Comment by br76530067** [comment]
Yes, it is same ,but some difference, for example, 12.5V in utility, 13.6V in voltmeter.
Let me check #5

**Comment by br76530067** [comment]
"In any case, it is not OK that measured APD voltage (63V) is not the same as set target voltage (128V). It is look like APD step-up converter or APD voltage measurement circuit are working wrong." as your repled in #5, let me check if it is .

**Comment by iliasam** [comment]
13.6 / 12.5V = 1.088, -> ~9% error, which is big. Can you measure difference at higher voltage  (40-50V)?

**Comment by br76530067** [comment]
when  47.3V in utility, 46.4V in voltmeter

**Comment by br76530067** [comment]
"Don't try to switch to Auto mode until you get well working manual mode." you mean first use the PWM duty to get higer voltage then use the AUTO mode to set?

**Comment by br76530067** [comment]
And one more : when 13.8V in utility, 11.9V in voltmeter

**Comment by br76530067** [comment]
"Hello.The APD voltage's problem solved. The problem is the inductor L5 type not value.
The manufacturer gave a multilayer inductor, but the actual winding type. There is no description about L5 type in the BOM."
I think it is same issue, I will buy this one and to try.

**Comment by iliasam** [comment]
"you mean first use the PWM duty to get higer voltage then use the AUTO mode to set?"
You need to get stable high voltage  (< 110V) by setting PWM duty manually.

**Comment by br76530067** [comment]
Hi, iliasam,
Thanks for your advice, after changing to the leading inductor, I got below picture:
![image](https://user-images.githubusercontent.com/41344495/129736688-99602229-3c5d-412f-998c-ebf4901c1131.png)
![image](https://user-images.githubusercontent.com/41344495/129736720-f1254002-5c05-4113-83aa-13326e0f2f6b.png)

![image](https://user-images.githubusercontent.com/41344495/129736762-35047c2d-ee35-472b-82d0-6edef1f26fdb.png)

![image](https://user-images.githubusercontent.com/41344495/129736789-6a51a367-85f6-46ab-9aab-4ed5c8db7e9f.png)

![image](https://user-images.githubusercontent.com/41344495/129736810-20a08f2a-cc89-4c6a-9380-0ff0b8a2fe98.png)

And after changing to the high precise resister, I got the 103.7V on voltmeter and 103.1V on PC utility.

**Comment by br76530067** [comment]
but what max volt I could achieve is 122V, is it correct?

**Comment by iliasam** [comment]
Breakdown voltage of MTAPD-07-013 is in 120-130V.
When APD is installed, you can the that APD is close to breakdown by seeing more noise at the TIA output.
Also, APD voltage would increase slowly (comparing to low voltage - not breakdown mode) as shown here: https://github.com/iliasam/OpenTOFLidar/blob/develop/Images/APD_voltage_vs_PWM.png (for AD500-8).

**Comment by iliasam** [comment]
But it is strange that you can't get 130V. Do you have APD installed or not?
What is the maximum PWM value that you have set?

**Comment by br76530067** [comment]
No, I havent installed the APD, and my APD tupe is MTAPD-07-007.

What is the maximum PWM value that you have set?
200 steps, as above picture.

**Comment by br76530067** [comment]
![image](https://user-images.githubusercontent.com/41344495/129742207-f0323f8b-9f69-42ef-a2e8-c58b9767e8e2.png)

**Comment by br76530067** [comment]
![image](https://user-images.githubusercontent.com/41344495/129742380-21916bbe-e203-46d7-ad7b-9f9a9ca7eb29.png)

**Comment by br76530067** [comment]
MTAPD-07-013 is on the delivery way

**Comment by iliasam** [comment]
The plot that I mentioned earlier, was measured with AD500-8 which have breakdown voltage ~95V. This plot is for information only.
This image is from "Issue 5": https://user-images.githubusercontent.com/48154419/92838938-f75e5f80-f411-11ea-96e4-dbe952ec430b.png
You can see that "Anesthesia-RW" can get 124.5V at 72 PWM steps.
I get 130V at 73V: https://ibb.co/vjFfwVD
All these measurements were made with APD installed, but I don't think that it is important.

Cleaning PCB could be important. 
Check R8, R9 values, check that C10, C11 are high-voltage capacitors.

**Comment by br76530067** [comment]
After clearing the PCB, I could get the maximum volt is 126V.
I just put here some soldered components' type, maybe you have some clue.
![image](https://user-images.githubusercontent.com/41344495/129760099-1c76a653-0c9b-4a36-926d-1fc4e56b5d9a.png)

For the BEAD, maybe I could just shorten it to try? because I think the BEAD may absorb some volt?

**Comment by iliasam** [comment]
Your Q1 and D1 are looking OK.
You can try to shorten L4, but I don't think that this will help.
Maybe it is really problem with C10,C11 working woltage?

**Comment by br76530067** [comment]
Because in china market, the  MTAPD-07-013 needs too long to get, and there is no AD500-8, So I buy a AD500-9 to try.
![image](https://user-images.githubusercontent.com/41344495/129828791-68ce108c-7036-4db2-9486-c87e499f93df.png)

Do you think the AD500-9 will work?

**Comment by iliasam** [comment]
Why there is no AD500-8? https://aliexpress.com/item/32396227457.html
Also I can see them in Taobao.
It looks like AD500-9 have higher breakdown voltage, than AD500-8. Also, you need to remade PCB for any leaded APD.
I think you need to find out why your circuit can't produce higher voltage.

**Comment by br76530067** [comment]
Oh, thank you for your reminder, after several times of searching in Taobao, I found one AD500-8.

"I think you need to find out why your circuit can't produce higher voltage."
I will try more.
