### ISSUE TITLE
Low-cost 3D scanner

### ISSUE THREAD

**Issue by DeRuiY** [iliasam/OpenTOFLidar#12]
I have been able to get a two-dimensional point cloud. I would like to DIY a low-cost 3D scanner based on your design. What do you recommend? thanks  
![image](https://user-images.githubusercontent.com/83878142/146761113-799053f9-3187-4445-af57-390d29a6dad4.png)

**Comment by iliasam** [comment]
Firstly I need to say that you have certain problems with calibration. Probably you need to set correct "BIN Length" value.  

If you are planning to make 3D scanner, you need to add another drive to rotate whole LIDAR.   
Example: https://youtu.be/3SnqrfDCc70  
P.S. I'm interested in any information about this Lidar from others, so your experience with this Lidar will be really interesting for me.

**Comment by iliasam** [comment]
@DeRuiY  Please, close this issue if you don't have other questions.

**Comment by DeRuiY** [comment]
Hello, I have come, I have been thinking about the ranging problem of TDC-GP21, because I used TDC-GP22 for a while before. Why do you want to measure distance this way, instead of using
![image](https://user-images.githubusercontent.com/83878142/154018006-a27a4928-330e-40ef-8a23-25edcea33b04.png)
instead of the way below
![image](https://user-images.githubusercontent.com/83878142/154018132-3385412f-f1b2-44f3-90e6-1815193aafe8.png)
![image](https://user-images.githubusercontent.com/83878142/154018310-bc4a9a9c-8ad3-4458-b234-1aca07a6314f.png) .Thanks

**Comment by iliasam** [comment]
Hello. 
Sorry, but I don't understand your question.
What is the "ranging problem of TDC-GP21" ?
My correction is used for compensating pulse amplitude/changing (exponential part) and for zero offsets compensation.
See https://github.com/iliasam/OpenTOFLidar/wiki/TDC-data-processing
