### ISSUE TITLE
Questions on encoder and disc

### ISSUE THREAD

**Issue by buzzzzm** [iliasam/OpenTOFLidar#18]

**Comment by buzzzzm** [comment]
hi,iliasam,
I have tried to follow the Electronics-assembling notes and test my advice in no-scanning mode.
I found my encoder can’t detect the disc with 65 silts, so I replaced it with a 20 silts disc.
![image](https://github.com/iliasam/OpenTOFLidar/assets/97682241/b4c1696f-d818-4592-a491-de000181d1c8)
![image](https://github.com/iliasam/OpenTOFLidar/assets/97682241/0f4b94b8-bbad-4306-a1ce-2dd2cdbebe76)

When I use the hex file you give, the “testing utility” showed “0x8”-wrong number of encoder events. 
![1](https://github.com/iliasam/OpenTOFLidar/assets/97682241/5a66147e-a38a-45fc-9a40-96c637b3744f)


So, I changed the parameter “ENCODER_HOLES_CNT” to 20.
But the data is not displayed when I run the “testing utility” again. why???
![2](https://github.com/iliasam/OpenTOFLidar/assets/97682241/ffbbe670-c065-4240-8d06-75c45af1eef3)
![image](https://github.com/iliasam/OpenTOFLidar/assets/97682241/c0b5dd2c-a86f-4f06-a761-66e5095fdc98)

Can I change the disc to a 20-slits one?  
Or what model of the encoder can detect a 65 silts disc? I want to know the product model. The one I bought doesn’t work well.

**Comment by iliasam** [comment]
First question - is your Lidar working well in non-scanning mode?
Possibly FW should work with encoder disc with 20 slits, if you **rebuild** the firmware.
Have you checked that your encoder is working well with an oscilloscope?
I can't give you model of my encoder sensor, because I take it from old printer. 
Maybe RPI-352 sensor will work well.

**Comment by buzzzzm** [comment]
First, I tested in no-scanning mode, is it working well?
The pictures are calibration page and no optics test results.
![image](https://github.com/iliasam/OpenTOFLidar/assets/97682241/5f8d2110-2a6c-434c-9638-d3e62dc9d66d)
![image](https://github.com/iliasam/OpenTOFLidar/assets/97682241/3803ed4e-54e6-473b-910a-d3a41f45238e)
![image](https://github.com/iliasam/OpenTOFLidar/assets/97682241/d693d081-66ab-42fe-abae-2d68c6e18388)
![image](https://github.com/iliasam/OpenTOFLidar/assets/97682241/f1ba6cef-8b72-4911-ab36-0f540c155301)
![image](https://github.com/iliasam/OpenTOFLidar/assets/97682241/f32eef35-6f84-44cf-95b7-a28cd3f21e2c)

I checked the encoder with an oscilloscope.

![29807c692123410447651bf6cae8821](https://github.com/iliasam/OpenTOFLidar/assets/97682241/1802cd27-b7b2-4c90-82cc-d2900f421a77)

I will buy the RPI-353 sensor and test with 65 silts disc.

**Comment by iliasam** [comment]
Your results in non-scanning mode are looking OK.
Oscilloscope picture from the encoder is looking well, too. I can't say now what is the problem.
You can check MCU pin 10 with oscilloscope to ensure that encoder pulses are getting to the MCU.
Also I can see that "BIN length" is NaN at your first photos. This is not correct.

**Comment by iliasam** [comment]
[scanning_fw_20_holes.zip](https://github.com/iliasam/OpenTOFLidar/files/11966272/scanning_fw_20_holes.zip)
You can try this FW - I build it for encoder with 20 holes. Also I had increased ENCODER_TIMEOUT_MS value to 25 ms.

**Comment by buzzzzm** [comment]
I downloaded the hex file you just sent, but the testing utility doesn't work.
And the BLDC motor rotates at a faster and unstable speed. 
![未命名1688643266](https://github.com/iliasam/OpenTOFLidar/assets/97682241/b6798fbb-5cfa-4e9a-9113-8802c5b92c38)
And I downloaded the hex file "scanning_fw_pcb_v4" again, the state mask is 0x8.
The motor starts fast and then slows down, eventually stabilizing its rotation.
![image](https://github.com/iliasam/OpenTOFLidar/assets/97682241/d4ac6182-8c39-4f28-812f-c5bda4c1c83c)

![222](https://github.com/iliasam/OpenTOFLidar/assets/97682241/43d9b180-e29b-4547-bc8e-ff461b7ec4a7)

**Comment by iliasam** [comment]
You can try to use "scanning_fw_20_holes" FW
and set speed of the motor manually at the "Motor Settings" page - see "Motor Manual PWM" -> "Set" button.
Do "Motor Speed" value is measured OK in this mode?

**Comment by iliasam** [comment]
Do you have any progress with your problem?
