### ISSUE TITLE
I have a problem with Vlaser waveforms

### ISSUE THREAD

**Issue by tmdwhsh** [iliasam/OpenTOFLidar#20]
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/fc6dffec-d18e-42cd-aec9-d7c273d36bff)
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/a754031f-34f5-458c-ac05-e212408fddb7)
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/cc01155c-5244-4705-bcd2-eba99043dc22)
I measured the VLaser at the J2 terminal, but could see that it did not match the ideal waveform you posted (LaserV_10~16V).
I could see that the amplitude was very large, around 13V, and the overall shape didn't match either.

I measured from J2 using the U.FL terminal and the measurement instrument was a Tektronix TDS 2012C.
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/59de8083-a5d6-4def-be32-686b41854682)

**Comment by iliasam** [comment]
How do you connect your U.FL cable to the oscilloscope?
 Is D7 installed right?

**Comment by tmdwhsh** [comment]
I didn't have a U.FL to BNC cable, so I connected a U.FL to SMA cable and an SMA to BNC cable to connect the U.FL terminal of J2 to the oscilloscope.
![-302085782658985113.jpg](https://github.com/iliasam/OpenTOFLidar/assets/43981588/22388ca2-410c-49a5-9be5-0fabcf69ae8b)

![2082348259-1994529926.jpg](https://github.com/iliasam/OpenTOFLidar/assets/43981588/a4c9ee6b-0f84-4b53-8a48-dbf42472746c)




The photo shows the D7 and everything else installed.

Could the above problem occur if the D7 was not installed properly?

I could try replacing the D7 with a new part or reversing the orientation of the D7 and installing it.
![Screenshot_20230726_031651_Chrome.jpg](https://github.com/iliasam/OpenTOFLidar/assets/43981588/32624455-a098-4e47-9f5a-05fb979554e6)

**Comment by iliasam** [comment]
"Could the above problem occur if the D7 was not installed properly?"
Maybe.
Can you give me a photo of your laser diode (PCB from other side)?

**Comment by tmdwhsh** [comment]
![20230726_123949.jpg](https://github.com/iliasam/OpenTOFLidar/assets/43981588/7df09923-d525-4490-942b-a839379d42ba)

![20230726_124153.jpg](https://github.com/iliasam/OpenTOFLidar/assets/43981588/acc79bc6-902a-45d5-b0a0-27c7a60246ee)

I was able to see the laser light up using a camera and IR detector card.



I will try to replace the D7, starting with what you said

**Comment by tmdwhsh** [comment]
![20230726_170947.jpg](https://github.com/iliasam/OpenTOFLidar/assets/43981588/582bd5ac-f4cb-4e78-92f0-ddd5f5e58a97)

I reversed the connection of the D7 and noticed that the amplitude of the waveform decreased, but it still doesn't look normal.

**Comment by iliasam** [comment]
"I reversed the connection of the D7 and noticed that the amplitude of the waveform decreased, but it still doesn't look normal."
You need to install diode as it is drawn at the schematic, this diode has a marking line near cathode.

Did you measured with voltmeter voltage at the R18, C17?
Have you selected right divider (1:1) at the oscilloscope channel which is connected to the UFL?
Is Q2 transistor soldered well?
You can check with an oscilloscope probe voltage shape at all lines of Q2.

**Comment by tmdwhsh** [comment]
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/3b5449ba-6147-4f9a-8a79-9312393fa160)
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/2a2ca855-f587-4403-aa46-168def30c7c9)
First, I thought that the flat part on one side was the Cathode, just like a normal LED, but after looking at the data sheet of SPL90_3, I realized that the flat part was the Anode, so I installed D7 accordingly.
But even after that, the waveform was still the same.

First, I checked the voltage of R18 and C17. 
R18 was measuring a very low voltage,
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/de48477c-f535-4f73-9e9c-a6609cf2ee3c)
C17 was measuring a high voltage of 18-20V.
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/f4c25444-2032-4caa-9f4f-c1447fe53dfb)
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/c469841a-d9f9-4880-a8d8-cc0b0d8512ff)

Next, I measured the voltage across the Drain, Gate, and Source of Q2.
For the Drain, we found the same voltage as C17,
For the Gate, it measured around 20V as shown below.
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/67bbc914-18ff-4185-8b48-73dbc683e424)
For the Source, it was measured as shown below.
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/5edc4111-7153-4d30-9722-a38e9d971290)
The soldering condition of Q2 looks normal.

**Comment by iliasam** [comment]
Your laser diode polarity is OK, I checked it. Cathode of D7 is marked by white dot at the PCB.
"C17 was measuring a high voltage of 18-20V."
This is not OK, C17 must be charged to a "Vlaser". Maybe you set too high laser voltage at the PC software or DC-DC (DA1) is producing too high voltage. DA6 maximum voltage is 18V, so it can be damaged by such high voltage.
Q2 is also not designed for high voltages. So you need to decrease  "Vlaser" to at least 16V.

Your measurements at the Q2 really differ from mine; I published today new images: 
https://github.com/iliasam/OpenTOFLidar/tree/develop/Images/Oscilloscope
"[laser_transistor_gate.png](https://github.com/iliasam/OpenTOFLidar/blob/develop/Images/Oscilloscope/laser_transistor_gate.png)" and "[laser_transistor_source.png](https://github.com/iliasam/OpenTOFLidar/blob/develop/Images/Oscilloscope/laser_transistor_source.png)"

Are you using x10 divider at your oscilloscope probes?

You can try to remove Q2 and measure  shape of the signal at the DA6 pin 2 (connected to the gate of Q2)?
It must have the shape, as drawn here: [laser_transistor_gate.png](https://github.com/iliasam/OpenTOFLidar/blob/develop/Images/Oscilloscope/laser_transistor_gate.png) - rising edge must be super fast.

Also, can you remove packet from the screen of your oscilloscope, I can't see grid time at it.

**Comment by tmdwhsh** [comment]
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/98add98e-d413-408e-a121-f7a8fcbd37eb)
First I set the Vlaser to 16V, got a clear oscilloscope screen, and measured the Drain, Gate, and Source voltages again. 
![Untitled-1](https://github.com/iliasam/OpenTOFLidar/assets/43981588/b7916057-1f90-44e6-ae03-d615388034d5)
Now I'm going to remove Q2 and measure it the same way and upload it again.

**Comment by tmdwhsh** [comment]
This is the waveform of pin 2 of DA6 after removing Q2.
![Untitled-31](https://github.com/iliasam/OpenTOFLidar/assets/43981588/d6d1ff52-a1c8-4b1f-9567-f0dac3134c6b)

**Comment by iliasam** [comment]
"First I set the Vlaser to 16V"
But did you measure Vlaser with voltmeter? MCU do not measuring Vlaser, so you need to check that electronics is working OK by yourself.
I can see that you did something, so the shape of voltage at the gate changed (photo from 14:46), now it is looking OK.
Other photos now are looking similar to mine. So you can install Q2 back.
_DA6 pin 6 is not a Gate line._
Did you try to remove UFL cable and measure voltage at the J2 directly with oscilloscope probe? I recommend to use "ground spring" for that: https://electronics.stackexchange.com/questions/40420/what-is-the-name-of-this-springy-type-oscilloscope-probe-accessory

**Comment by tmdwhsh** [comment]
Sorry,, That was DA6 pin 2.

First, I verified with a multitester that the Vlaser is 16V.
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/35d540c9-5503-4af6-a148-446c6ca3c4ad)

Next, I measured with the default probe(X10) instead of the U.FL.
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/9435b305-0713-4b11-b482-7fd462d21900)
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/fcb7ba0f-572c-46b7-9eca-598d955361a3)

**Comment by iliasam** [comment]
I still don't understand what is shown at the photo from 16:44.
Looks like that yellow CH1 is still a signal from UFL, but UFL cable must be disconnected from PCB for tis measurement.

**Comment by tmdwhsh** [comment]
I assumed the small terminal next to J2 was the same as the UFL terminal, so I measured it as shown below.
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/ea9f2daa-53f0-4a5d-984e-dc9c08732f4b)
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/41a57dc8-200a-4cef-bb01-f536eab29c5f)
Of course, the GND line of the probe was connected to the GND of the PCB.

**Comment by iliasam** [comment]
UFL cable must be disconnected because it create affect to a signal - cable has its own capacity.
It is OK to measure signal at the pin of the UFL connector as you did.
And I repeat again - use "ground spring" to get better results. "Ground spring" is short, so it has less inductance.

**Comment by tmdwhsh** [comment]
I took another measurement using a ground spring! (I ordered one from Aliexpress today, but it took a while to ship, so I made a similar one using copper wire)
Does this represent a good enough waveform to proceed to the next step?
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/8439447f-af1b-46ab-93f7-9190e3bb5172)
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/7592f9c4-4d64-46d9-a922-c4299a80043c)
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/45938f6f-04c7-4eb9-964c-843287af34ae)

**Comment by iliasam** [comment]
Yes, now waveform is looking OK, but it will be helpful for you to find out why UFL cable is producing bad signal.
You will need to use another UFL cable (J1 connector) for photodiode lens alignment, and you can see the same problem there.
You can try to replace R20 to 47 ohm or 100 ohm and check signal from the UFL cable.
