### ISSUE TITLE
Calibration and scanning problem

### ISSUE THREAD

**Issue by tmdwhsh** [iliasam/OpenTOFLidar#21]
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/54903f4d-b4c8-4a00-bbf1-894509128c1f)

I got the error "bit2 (0x4) - Wrong hits number from laser comparator" as shown in the photo above and I can't proceed any further.

What can I do to fix a situation like this?

**Comment by iliasam** [comment]
Try to check DA5 output with oscilloscope.

**Comment by tmdwhsh** [comment]
The above problem occurred while creating the second Tof Lidar!
I'll take your feedback into consideration and keep working on it.

I am in the process of calibrating my first Tof Lidar, measuring distances and calibrating it. 
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/53f89848-fe70-493a-a985-b80f75cf71b9)
I used the Non-Scanning Firmware to set the Refence Distance and compared the value measured by the Testing Utility with the actual measurement using a tape measure and found that I got a very accurate value.

However, due to an incorrect calibration method, the Calibration Graph does not come out ideal (similar to yours) and the Scanning Test Utility does not come out correctly. 

Firstly, can you give me a step by step on how to calibrate?
We recorded the data in the following way
1. Upload Non-scanning Firmware.
2. obtained the actual reference length for measurement using a tape measure.
3. set a target for measurement using a wide plate.
4. The measurer stands with the plate at a close point (Ex: 1M), and the Lidar is pointed at the point, and the Reference Distance is set to 1000mm.
5. Start Slow Decoding, and Pressed Start button(Capture Button, top left). 
6. The measurer moved away sequentially (0.5M increments), changed the Reference Distance to match, and pressed the Start button (Capture Button) again.
7. repeat the process of Step 6 and use it to get the Calibration Graph and Coefficient.
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/aa6dea6d-64fd-411c-a5ca-d2d17723f962)
8. After uploading the scanning firmware, send the coefficient obtained in Step 7 to the MCU.
9. Scanning was performed using the Scanning test Utility.

I'm afraid I've done it the wrong way.

**Comment by iliasam** [comment]
Please do not mix different questions in one issue!

"Firstly, can you give me a step by step on how to calibrate?"
Please, read Wiki carefully: https://github.com/iliasam/OpenTOFLidar/wiki/Walk-error-calibration
Yes, you do calibration wrong.

**Comment by tmdwhsh** [comment]
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/c1189e26-ff7f-4c56-9415-0ebecf563222)
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/605ee905-7981-49ba-b2f9-db7c5c3d3add)
![image](https://github.com/iliasam/OpenTOFLidar/assets/43981588/f6f9db95-de2a-47ec-ac79-d872527321ad)
I tried calibrating again and got the same results as above. 
Something seemed to be wrong with the maximum value on the y-axis being below 1000 (your image went up to 2000).

But first, I uploaded the scanning firmware, sent the coefficients to the MCU, and tried scanning.

https://github.com/iliasam/OpenTOFLidar/assets/43981588/ca14adee-58b8-40cb-b35f-e63e57ac6150

In non-scanning mode, the distance was measured accurately. However, when the scanning test was performed after uploading the coefficients from the calibration data above, the distance measured was smaller than the actual value, even though it appeared to measure the shape of the actual structure.
Also, when there was an obstacle or person at a certain point in front of the LiDAR, the scan seemed to work fine, but when the obstacle or person disappeared from the area, the overall scan result would shrink to the center.

https://github.com/iliasam/OpenTOFLidar/assets/43981588/29567502-36ba-4a77-8141-b0ccf614362a

**Comment by iliasam** [comment]
Did you install "Reference Plate" to your Lidar?
This plate is not described well in Wiki, but it was mentioned in the original article: https://habr-com.translate.goog/ru/articles/485574/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en&_x_tr_hist=true
Distance between plate and rotation axis is set in code: https://github.com/iliasam/OpenTOFLidar/blob/f3f400fe56a28f5006bd249ed1249cb4261fe623/Firmware/scanning_fw/config.h#L24

**Comment by tmdwhsh** [comment]
I checked the Reference Plate as you said, and after mounting the Reference Plate and adjusting the zero point of the Encoder Disk appropriately, I confirmed that the scanning result is observed normally.



https://github.com/iliasam/OpenTOFLidar/assets/43981588/165cc304-0ab3-4e47-b368-f17c6312b024
