### ISSUE TITLE
Laser constantly pulsing in no scanning mode?

### ISSUE THREAD

**Issue by taliaxu09** [iliasam/OpenTOFLidar#22]
Hello! Great project! Thank you so much for developing this.

I originally thought that the laser is only pulsing when "start" or request batch is pressed in the PC utility in no scanning mode, however, using a photodiode, it seems that the laser is constantly pulsing at 1KHz even with no command from PC utility. I just wanted to check that this is as designed?

**Comment by iliasam** [comment]
Hello.
You are right, but it is mentioned here: https://github.com/iliasam/OpenTOFLidar/tree/develop/Firmware in readme.md
Blinking is controlled from main.c

**Comment by taliaxu09** [comment]
That makes sense! I was a bit confused by the utility because I thought maybe pressing start initiates the 1 kHz pulse until it's done sampling

I measured the waveform at J2 and I think this looks pretty good (Laser voltage is 16V)?
![20231109_130139](https://github.com/iliasam/OpenTOFLidar/assets/86804927/5122ff26-a589-4dd0-88e4-bd810330b31a)

Thank you again for making this project!

**Comment by iliasam** [comment]
I think that shape of the signal is OK.
