### ISSUE TITLE
I have a question about LidarTestingUtility.

### ISSUE THREAD

**Issue by pikasm** [iliasam/OpenTOFLidar#23]
Hello, there was no pulse in my previous TDC. At that time, the request of the program was correct. Now TDC has a pulse and it becomes N/A. Does this mean that my single chip microcomputer is broken?
<img width="765" alt="1700474085815" src="https://github.com/iliasam/OpenTOFLidar/assets/147833145/97113a78-66fa-42ae-946d-3af9b473e3af">

**Comment by iliasam** [comment]
Hello.
Is MCU flashed with right firmware?
Check your UART connections.
Check that MCU quartz oscillator is soldered well, wires from  quartz  to MCU is OK.
Do LED blinking? How fast?

**Comment by pikasm** [comment]
I tested the frequency of LED. It's 5HZ.

**Comment by pikasm** [comment]
![Uploading 微信图片_20231120182430.jpg…]()

**Comment by pikasm** [comment]
Here are my test results.
![微信图片_20231120182430](https://github.com/iliasam/OpenTOFLidar/assets/147833145/6d09d189-f9ab-4551-a8ae-3e6993273a4e)

**Comment by pikasm** [comment]
Should I check if there is something wrong with MCU next? 
But my TDC pulse is correct, DA6 also has pulses, J2 also has pulses. 
Should I reinstall a DD2?

**Comment by iliasam** [comment]
Maybe it is really something wrong with MCU, but It is strange that other functions are working, and UART is not working.
Try to check soldering MCU pins 39/40.
You can check with an oscilloscope MCU RX/TX lines when PC is sending requests.

**Comment by pikasm** [comment]
Then I'll check it. Thank you.

**Comment by pikasm** [comment]
I replaced the single chip microcomputer and got a signal. Thank you so much. I am so happy.
