### ISSUE TITLE
Increasing pulse width and frequency

### ISSUE THREAD

**Issue by taliaxu09** [iliasam/OpenTOFLidar#25]
Hello, I would like to increase the power output by increasing the pulse width to be as close to the maximum (I believe 100 ns?) as possible and also increase the frequency from 1 kHz to maybe 5 kHz or 10 kHz.

Would you point me to where I could change this in the code? Can I increase the pulse width by using a larger capacitor?

**Comment by iliasam** [comment]
Hello.
1kHz is just test signal frequency, see main.c of "not_scanning_fw" project (TIMER_ELAPSED(timer_1ms) part).
"scanning_fw" reach 10kHz pulse frequency at 15 RPS motor speed.

You can try to increase pulse width by using a larger capacitor, but be careful!

**Comment by taliaxu09** [comment]
Thank you! What would be the best software version / setup to compile the code?

**Comment by iliasam** [comment]
I don't know what is your hardware, do you need scanning or not, so I can't help you.

**Comment by taliaxu09** [comment]
I built it as yours, and I don't need scanning and the motor, I am just using the laser.

I just wanted to know the best setup to be able to compile the code (I only used Keil uvison before) because I saw in another thread that there might be problems if the version is different.

**Comment by iliasam** [comment]
I use IAR 7.50 for building this FW.

**Comment by taliaxu09** [comment]
Sorry to bother you again, not very familiar with embedded coding..

I see that timer_1ms seems like the fastest time the timer can recognize, since the increment is ms_tick which ticks every ms? What would be the easiest way to change this to 0.1ms?

**Comment by iliasam** [comment]
Software counters, like "timer_1ms", are based on "ms_tick" variable, that is incremented in SysTick_Handler(), which is called by system timer with 1ms period.
This timer is configured by SysTick_Config() function in "hardware.c".
A lot of code here is expecting that this timer has 1ms period.

One option is use hardware CAPTURE_TIMER, that is used in "scanning_fw". It can generate interrupts with needed frequency.

Another way - you can use hardware_dwt_get() function, that return MCU tick count (72 ticks per 1us). 
You can see dwt_delay_us() function.
But this kind of delay will lock program execution.

**Comment by taliaxu09** [comment]
Thank you!

**Comment by ShanLan12** [comment]
Hello, I have a question for you, I recently came across a piece of code in my project which uses the MS1005 chip using the stop1 channel and stop2 channel connected to the same pin. A rising edge trigger and a falling edge trigger can be used to get the pulse width and use this pulse width to calibrate the distance measured. May I ask why it does this and how it calibrates the distance
<img width="563" alt="2f4c7ef02ac0cc7412980e3b03d72d6" src="https://github.com/iliasam/OpenTOFLidar/assets/129259026/302f9747-9315-49de-a21c-b0c01729b895">
<img width="760" alt="cd89776f09df7566da640947f878571" src="https://github.com/iliasam/OpenTOFLidar/assets/129259026/ea5a8332-04da-4916-8ed3-5573aaf0f2f7">
Thank you!

**Comment by iliasam** [comment]
[ShanLan12](https://github.com/ShanLan12) Please, create new issue for your question.
