### ISSUE TITLE
What is the ref_plate_distance 

### ISSUE THREAD

**Issue by AbidHussain70** [iliasam/OpenTOFLidar#4]
Hi,

**Whats this REF_PLATE_DIST variable?** 
https://github.com/iliasam/OpenTOFLidar/blob/d2ed102225cc642949f4d09c30fa0e5a3a8fc32a/Firmware/scanning_fw/config.h#L26

**is it this back plate?**
![1806252180](https://user-images.githubusercontent.com/23444211/80573493-a46fa700-8a32-11ea-83b0-16f92954698d.jpg)

**Or is it this top plate distance?**
![1597861059](https://user-images.githubusercontent.com/23444211/80573456-8d30b980-8a32-11ea-9461-09c7bb6953ac.jpg)

**Comment by iliasam** [comment]
"Reference plate" is a white plastic plate (you marked it at the first picture). LIDAR could "see" this mate when mirror is turned to zero angle. (At upper pictures mirror is at ~180 deg position).
LIDAR is measuring all distance from the rotation axis in horizontal plane.
So "REF_PLATE_DIST" is distance in mm between the rotation axis and the "Reference plate"

**Comment by AbidHussain70** [comment]
Great, I got it.

Thanks
