### ISSUE TITLE
The pulse on LASER_PULSE net should be like this？

### ISSUE THREAD

**Issue by br76530067** [iliasam/OpenTOFLidar#8]
I soldered these components on PCB under your instruction note " #2. install TDC, its quartz. Enable "Auto Request Batch" in utility. There must be pulses at "LASER_PULSE" net. ", and I use an oscilloscope to see the signal on LASER_PULSE net, are these data in the following picture correct?
The test PC utility:
![image](https://user-images.githubusercontent.com/41344495/128537322-b9a49ef8-2e3b-477c-a03a-febc9efe0151.png)

The oscilloscope:
![image](https://user-images.githubusercontent.com/41344495/128537685-a631295c-f391-4687-bf11-fea0fd2952aa.png)

Thank you in advance!

**Comment by iliasam** [comment]
Pulses shoud have ~1 ms period and they should have 3.3V amplitude.
I can see from your screenshot that "state mask" is 0x5. Description is here: https://github.com/iliasam/OpenTOFLidar/wiki/State-Mask-bits-description
You have bit 0 set which mean that MCU can't detect TDC at startup.
Have you installed all componencs aroung TDC?

**Comment by br76530067** [comment]
Hi, iliasam, thank you for your reply
I installed all components around TDC, and I checked the voltage level of every pin of that, it looks like normal.

#1  And I found the temperature of the soldering for TDC is limited to 260 °C in the datasheet, due to manual soldering, I used 350°C to solder TDC, which may cause the broken of TDC?  have you ever met this situation when you solder TDC?

#2 Or do you have some way to check if TDC is broken?

**Comment by br76530067** [comment]
Hi ilisam 
it looks like get some progree, however, i cant catch the pulse on LASER_PULSE net.
![image](https://user-images.githubusercontent.com/41344495/128583222-33bc58d4-b399-417c-aa8f-4f2baadcf611.png)
![image](https://user-images.githubusercontent.com/41344495/128583370-06f3d81e-66e8-49c2-a444-e8c4d812716b.png)

**Comment by iliasam** [comment]
Pulses should be short, with 1us width. Set trigger to 1V at your oscilloscope.
I don't know how to find out that TDC is broken.

**Comment by br76530067** [comment]
Hi, iliasam,

I under your hint, and get this picture in the oscilloscope, but it looks like only could get one time of rising edge when power is on. Then can not get any pulse anymore, is it correct?
![image](https://user-images.githubusercontent.com/41344495/128601873-d8f41b07-cd25-4264-b938-c41aa4303099.png)

Thanks in advance

**Comment by iliasam** [comment]
Pulses should be present continuously when "Auto Request Batch" flag is set.
Also you can try to press "Start" button.

**Comment by br76530067** [comment]
After changing a TDC-GP21, it works, Thanks, I will continue.
