### ISSUE TITLE
How to be able to see the laser light.

### ISSUE THREAD

**Issue by br76530067** [iliasam/OpenTOFLidar#9]
Hi, iliasam, 
I am working on step #4Install MOSFET, Laser diode, diode D7, and other lasers components. Check that laser is working by the camera. Do not look to the laser!! Check laser current pulses by connecting J2 to the oscilloscope. Current must change with changing "Vlaser".

however, I can not see the laser light on my iPhone camera, how do I make sure that is working?
![image](https://user-images.githubusercontent.com/41344495/128625466-a91c5fdd-5575-401b-9538-0e42242ca69f.png)

And I get the J2 oscilloscope picture like below ( because I do not have 0.1R resistance, so I use a 0.3R one), does the blow picture be correct?
![image](https://user-images.githubusercontent.com/41344495/128625537-fda23ca1-a108-448c-81e0-42e88d7f14e5.png)
![image](https://user-images.githubusercontent.com/41344495/128625549-88da6171-8d9f-4a3d-94f9-61a5ad2138a2.png)
![image](https://user-images.githubusercontent.com/41344495/128625553-e2832f9e-f2f5-4e6d-ab1d-3428f4feeb30.png)

Thanks in advance!

**Comment by br76530067** [comment]
And I can change the J2 signal by changing the Laser Volt on PC Testing Utility

**Comment by br76530067** [comment]
When set to 19V:
![image](https://user-images.githubusercontent.com/41344495/128625821-c1755e6a-23eb-4dcc-9c7b-3bbf292e6eda.png)
![image](https://user-images.githubusercontent.com/41344495/128625835-c19e4aa8-4304-476c-afa1-3d532a33926d.png)

**Comment by br76530067** [comment]
Ok thanks, I use a Huawei phone to get the laser light successfully, pls omit the laser light problem.
![image](https://user-images.githubusercontent.com/41344495/128625965-0bb96272-b3a5-4636-a695-e04105485618.png)

**Comment by iliasam** [comment]
And yes, laser is infrared, so different phones haw different IR filters. Best way is to use camera with no IR filters (like CCTV).
Using 0.3 Ohm is not good idea - you will lose too much voltage at it (~4.5V).
You can try to connect 3 resistors  0.3 Ohm parallel to get 0.1 Ohm, but I'm not sure how this will work (because of parasitic inductance of resistors).
Be careful with laser voltage - high voltage can damage laser!

How you are connecting oscilloscope to the board? The best way is to use U.FL - BNC cable.
Also it is possible to take coaxial cable with BNC connector and solder it instead of  U.FL connectors at PCB.
If you are using oscilloscope probe, you must use "oscilloscope ground spring": https://electronics.stackexchange.com/questions/40420/what-is-the-name-of-this-springy-type-oscilloscope-probe-accessory
Otherwise you would see a lot of oscillations.

**Comment by br76530067** [comment]
Yes, U.FL - BNC cable
![image](https://user-images.githubusercontent.com/41344495/128626294-4b69acc2-3c27-46df-985a-1e5611f393f1.png)
![image](https://user-images.githubusercontent.com/41344495/128626304-de4c96dc-f702-4679-b226-858ca841506e.png)

And I do not know why there will be a lot of oscillations, is it due to the inductance of the 0.3R resistor?
![image](https://user-images.githubusercontent.com/41344495/128626365-d921a786-0f7a-4125-b32b-b3f752e5688d.png)

**Comment by iliasam** [comment]
Yes, using leaded resistor is not good at all. 
Also is your oscilloscope have an ability to switch its input impedance to 50 Ohm, you should use it.

**Comment by br76530067** [comment]
Ok, and I will replace the leaded resistor with a 0.1Ohm resistor with a 1206 footprint.
![image](https://user-images.githubusercontent.com/41344495/128626843-7d0ddc30-ac62-4599-b2f2-095ee4780eb8.png)

**Comment by br76530067** [comment]
But I saw this 0.1Ohm resistor also is Leaded resistor, could you recommend a type of resistor for me to buy and replce? 
Thanks

**Comment by iliasam** [comment]
As you can see in BOM, you need  0805 (2012 metric) 0.1 Ohm resistor.

**Comment by br76530067** [comment]
Ok, Thanks!

**Comment by br76530067** [comment]
Hi, Iliasam, 
I replaced the 0.3Ohm lead resister with 0.1Ohm with 0805 footprints ( the type of this resister is 0.1Ohm, however, what I scale it by multimeter is 0.3Ohm). And I got the following pictures, should these pictures be correct? The laser voltage should be 10V because I haven't connected it to the PC to configure.
![image](https://user-images.githubusercontent.com/41344495/129209882-7e25b452-f1f4-4b30-a6c4-10d8db6ff013.png)
![image](https://user-images.githubusercontent.com/41344495/129209919-73b3ce77-fb3c-499b-bcae-f5c7960f678e.png)

**Comment by iliasam** [comment]
For me this picture is too strange, signal should not be such oscillating, but I can't really remember exact waveforms at low voltage. But the first pulse must be highest one, as I can remember.
Soldering flux should be removed from PCB (laser circuit). 
I can see that you have modified PCB comparing to my PCB, also I don't know what are the components that you are installed.

**Comment by br76530067** [comment]
Hi, Iliasam, thank you for your replying.
I haven't changed your PCB, I just add a MEMS mirror driver part to your PCB, because I want to use the MEMS mirror to replace the rotating mirror in your project, and I am willing to share with you all of this project and I will open this after finishing. Maybe you are interested in it if so I could share with you some work I did( but I only do a little...)

And I found the following picture after I use the probe instead of the U.FL - BNC cable.

**Comment by br76530067** [comment]
![image](https://user-images.githubusercontent.com/41344495/129218460-33d74b55-f634-4f63-9ffe-ec79ffe17e56.png)

![image](https://user-images.githubusercontent.com/41344495/129218490-c8efd031-a6f3-46ca-aa54-ea7ce1ad30f4.png)

![image](https://user-images.githubusercontent.com/41344495/129218511-97091c04-3cfb-417c-bee4-248c549352dd.png)

**Comment by iliasam** [comment]
This is looking better, but pulse width seems too big for me. It is strange, that probe give better shape, that a special cable.
You can try to change C17 to a smaller value to decrease pulse width.
Could you say your full laser marking?
Are you you using probe in x10 mode?

**Comment by iliasam** [comment]
I have added laser current screenshots from my oscilloscope (made with different voltages): https://github.com/iliasam/OpenTOFLidar/tree/develop/Images/Oscilloscope/LaserCurrent
These measurements are made with UFL cable, oscilloscope input is in high-impedance mode.

**Comment by br76530067** [comment]
Hi, Iliasam, 
#1,After changing the C17 20nf to 10nf, I got these pictures:
At 10V:
![image](https://user-images.githubusercontent.com/41344495/129352269-62bd1fa6-03b0-4174-9cc7-b519345315f3.png)
![image](https://user-images.githubusercontent.com/41344495/129352288-7d1bfbb5-8b6e-4a49-a857-f77f009c60c3.png)

At 11V:
![image](https://user-images.githubusercontent.com/41344495/129352339-95650d27-1d2a-4c75-b3f4-fcc35fdd3939.png)
![image](https://user-images.githubusercontent.com/41344495/129352350-9e575f2d-a6c1-4dd4-bd6c-340e4a024b1e.png)

#2, About: Could you say your full laser marking?
Sorry, what do you exactly mean?

#3 ,Are you you using probe in x10 mode?
No, I am in X1 mode.

Thanks!

**Comment by br76530067** [comment]
#4 and do you know why there is the signal? what is that? I did not found this signal in your picture.
![image](https://user-images.githubusercontent.com/41344495/129352581-1b962f9f-e162-4e94-9d0c-211250ab90cf.png)

**Comment by iliasam** [comment]
Now shape of the pulses is looking better, but pulse width is still ~50ns, while my pulse width was ~25 ns at 12V.
Maybe you need to decrease C17 more.

" About: Could you say your full laser marking?
Sorry, what do you exactly mean?"
I mean full name of your laser diode. I'm using "SPL PL90_3", number 3 is important. 

As I know, it is not recommended to use x1 mode for measuring high frequencies: http://electronics-diy.com/electronic_schematic.php?id=970

"#4 and do you know why there is the signal?"
It is some kind of spike at the end (falling edge) of controlling pulse "LASER_PULSE" which is 1 us long. It is now visible at my oscillograms because they are too short. It is OK.

**Comment by br76530067** [comment]
#1  I'm using "SPL PL90_3", number 3 is important.
Hi I am also using "SPL PL90_3"
![image](https://user-images.githubusercontent.com/41344495/129363340-ffd08473-c0b9-46c9-b36f-72a88b9104e9.png)

**Comment by iliasam** [comment]
OK, I was afraid that you are using another type of laser.

**Comment by br76530067** [comment]
After changing C17 to 3.3 UF ,I got :
10V:
![image](https://user-images.githubusercontent.com/41344495/129366778-898edf46-ef83-4bf0-afac-56e583e37047.png)

12V:
![image](https://user-images.githubusercontent.com/41344495/129366826-4f2678b0-c69f-42a6-983b-8f7c803b4e64.png)

**Comment by iliasam** [comment]
Ok, this is looking better, so I think that electronics is working OK now.
You can try to increase laser voltage to 14-15V.
It would be good to get somehow the same pictures with UFL wire.
